on:
  push

jobs:
  stuff:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up SSH
        uses: jacobsee/github-actions/configure-ssh-auth-sock@ssh-setup-action
        with:
          domain: ${{ secrets.GITLAB_DOMAIN}}
          private_key: ${{ secrets.GITLAB_PRIVATE_KEY }}
          ssh_port: 2222
          ssh_auth_sock: ./ssh_agent.sock
      - name: Clone repo
        env: 
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          # GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
          git clone "$GITLAB_REPO"
      - name: show stuff
        run: |
          ls .