jobs:
  stuff:
    runs-on: ubuntu-18.04
    container: bitnami/git
    steps:
      - name: Configure SSH
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "Updating known_hosts."
          ssh-keyscan gitlab.consulting.redhat.com >> ~/.ssh/known_hosts
          echo "Updated known_hosts!"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "Adding private key"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "Added private key!"
      - name: show stuff
        run: |
          ls .