on:
  push

jobs:
  stuff:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up SSH
        uses: jacobsee/github-actions/ssh-agent@ssh-agent-action
        with:
          domain: ${{ secrets.GITLAB_DOMAIN}}
          private_key: ${{ secrets.GITLAB_PRIVATE_KEY }}
          ssh_port: 2222
      - name: Clone repo
        env: 
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git clone "$GITLAB_REPO"
      - name: show stuff
        run: |
          ls .