jobs:
  stuff:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up SSH
        uses: jacobsee/github-actions/configure-ssh-auth-sock@ssh-setup-action
        with:
          domain: ${{ secrets.GITLAB_DOMAIN}}
          ssh_auth_sock: /tmp/ssh_agent.sock
          private_key: ${{ secrets.GITLAB_PRIVATE_KEY }}
      - name: Pull repo
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git pull ${{ secrets.GITLAB_REPO }}
      - name: show stuff
        run: |
          ls .